Repository MetricsHub/metricshub-community, pull requests merged in 2024-11, with the labels that each got.

#467 Issue #435: Add the possibility to use the same connector with different connector variables
  metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/config/AdditionalConnector.java
  metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/config/ResourceConfig.java
  metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/connector/AdditionalConnectorsParsingResult.java
  metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/connector/ConnectorVariablesLibraryParser.java
  metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/deserialization/ConnectorVariablesDeserializer.java
  metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/helper/ConfigHelper.java
  metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/helper/ConnectorTemplateLibraryParser.java
  metricshub-agent/src/test/java/org/sentrysoftware/metricshub/agent/context/AgentContextTest.java
  metricshub-agent/src/test/java/org/sentrysoftware/metricshub/agent/helper/ConnectorVariablesLibraryParserTest.java
  metricshub-agent/src/test/resources/config/metricshub-connectorVariables.yaml
  metricshub-agent/src/test/resources/connectorVariablesLibraryParser/connectorVariable.yaml
  metricshub-agent/src/test/resources/connectorVariablesLibraryParser/noConnectorVariable.yaml
  metricshub-doc/src/site/markdown/configuration/configure-monitoring.md
  metricshub-linux/src/main/resources/jpackage/metricshub/config/metricshub-example.yaml
  metricshub-windows/src/main/resources/jpackage/MetricsHub/config/metricshub-example.yaml
Labels: developer_tested

#481 Issue #289: Document the most common use case
  metricshub-doc/src/site/markdown/configuration/configure-monitoring.md
  metricshub-doc/src/site/markdown/usecases/custom.md
  metricshub-doc/src/site/markdown/usecases/network-interfaces.md
  metricshub-doc/src/site/markdown/usecases/ping.md
  metricshub-doc/src/site/markdown/usecases/process-windows.md
  metricshub-doc/src/site/markdown/usecases/service-health.md
  metricshub-doc/src/site/markdown/usecases/service-linux.md
  metricshub-doc/src/site/resources/images/metricshub-network-monitoring-snmp.png
  metricshub-doc/src/site/resources/images/metricshub-ping-check-feature.png
  metricshub-doc/src/site/site.xml
Labels: documentation

#488 Issue #484: Document the Prometheus and Grafana integrations
  metricshub-doc/src/site/markdown/installation/index.md
  metricshub-doc/src/site/markdown/prometheus/alertmanager.md
  metricshub-doc/src/site/markdown/prometheus/grafana.md
  metricshub-doc/src/site/markdown/prometheus/prometheus.md
  metricshub-doc/src/site/resources/images/grafana-metricshub-host.png
  metricshub-doc/src/site/resources/images/grafana-metricshub-main.png
  metricshub-doc/src/site/resources/images/grafana-metricshub-site.png
  metricshub-doc/src/site/resources/images/metricshub-prometheus-diagram.png
  metricshub-doc/src/site/site.xml
Labels: documentation

#487 Issue #470: Add support for `host.id`, `host.name`, and other attributes as arrays in resource configuration
  metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/deserialization/AttributesDeserializer.java
  metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/deserialization/PostConfigDeserializer.java
  metricshub-agent/src/test/java/org/sentrysoftware/metricshub/agent/context/AgentContextTest.java
  metricshub-agent/src/test/java/org/sentrysoftware/metricshub/agent/deserialization/AttributesDeserializerTest.java
  metricshub-agent/src/test/java/org/sentrysoftware/metricshub/agent/deserialization/PostConfigDeserializerTest.java
  metricshub-agent/src/test/resources/config/metricshub-multi-hosts.yaml
  metricshub-agent/src/test/resources/config/metricshub.yaml
  metricshub-doc/src/site/markdown/configuration/configure-monitoring.md
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/common/helpers/MetricsHubConstants.java
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/common/helpers/StringHelper.java
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/deserialization/MultiValueDeserializer.java
  metricshub-http-extension/src/main/java/org/sentrysoftware/metricshub/extension/http/HttpConfiguration.java
  metricshub-ipmi-extension/src/main/java/org/sentrysoftware/metricshub/extension/ipmi/IpmiConfiguration.java
  metricshub-linux/src/main/resources/jpackage/metricshub/config/metricshub-example.yaml
  metricshub-oscommand-extension/src/main/java/org/sentrysoftware/metricshub/extension/oscommand/OsCommandConfiguration.java
  metricshub-oscommand-extension/src/main/java/org/sentrysoftware/metricshub/extension/oscommand/SshConfiguration.java
  metricshub-oscommand-extension/src/test/java/org/sentrysoftware/metricshub/extension/oscommand/OsCommandExtensionTest.java
  metricshub-ping-extension/src/main/java/org/sentrysoftware/metricshub/extension/ping/PingConfiguration.java
  metricshub-snmp-extension/src/main/java/org/sentrysoftware/metricshub/extension/snmp/SnmpConfiguration.java
  metricshub-snmpv3-extension/src/main/java/org/sentrysoftware/metricshub/extension/snmpv3/SnmpV3Configuration.java
  metricshub-wbem-extension/src/main/java/org/sentrysoftware/metricshub/extension/wbem/WbemConfiguration.java
  metricshub-windows/src/main/resources/jpackage/MetricsHub/config/metricshub-example.yaml
  metricshub-winrm-extension/src/main/java/org/sentrysoftware/metricshub/extension/winrm/WinRmConfiguration.java
  metricshub-wmi-extension/src/main/java/org/sentrysoftware/metricshub/extension/wmi/WmiConfiguration.java
Labels: developer_tested

#483 Issue #480: Fix IpmitoolCommand
  metricshub-oscommand-extension/src/main/java/org/sentrysoftware/metricshub/extension/oscommand/OsCommandExtension.java
  metricshub-oscommand-extension/src/main/java/org/sentrysoftware/metricshub/extension/oscommand/ipmi/UnixIpmiCriterionProcessor.java
  metricshub-oscommand-extension/src/main/java/org/sentrysoftware/metricshub/extension/oscommand/ipmi/UnixIpmiSourceProcessor.java
  metricshub-oscommand-extension/src/test/java/org/sentrysoftware/metricshub/extension/oscommand/OsCommandExtensionTest.java
Labels: bug, developer_tested

#496 Issue #294: Monitoring Remote Linux
  metricshub-doc/src/site/markdown/usecases/remote-linux.md
  metricshub-doc/src/site/site.xml
Labels: documentation

#501 Issue #500: Mono-Instance collect processes only one monitor
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/collect/CollectStrategy.java
Labels: bug, developer_tested
