Repository MetricsHub/metricshub-community, pull requests merged in 2024-09, with the labels that each got.

#373 Issue #341: Define keys under monitor
  metricshub-agent/src/test/java/org/sentrysoftware/metricshub/agent/context/AgentContextTest.java
  metricshub-agent/src/test/java/org/sentrysoftware/metricshub/agent/deserialization/MonitorJobsDeserializerTest.java
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/common/helpers/MetricsHubConstants.java
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/connector/model/monitor/AbstractMonitorJob.java
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/connector/model/monitor/MonitorJob.java
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/connector/model/monitor/SimpleMonitorJob.java
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/connector/model/monitor/StandardMonitorJob.java
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/connector/model/monitor/task/MultiInstanceCollect.java
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/AbstractAllAtOnceStrategy.java
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/collect/CollectStrategy.java
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/telemetry/MonitorFactory.java
  metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/connector/parser/ConnectorParserTest.java
  metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/collect/CollectStrategyTest.java
  metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/collect/PrepareCollectStrategyTest.java
  metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/detection/AutomaticDetectionTest.java
  metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/pre/PreSourcesStrategyTest.java
  metricshub-engine/src/test/resources/test-files/connector/management/keys/monitorKeys.yaml
  metricshub-hardware/src/test/java/org/sentrysoftware/metricshub/hardware/strategy/HardwarePostCollectStrategyTest.java
  metricshub-hardware/src/test/java/org/sentrysoftware/metricshub/hardware/strategy/HardwarePostDiscoveryStrategyTest.java
Labels: enhancement

#387 Issue #385: Move Connectors Directory to Introduction
  metricshub-doc/src/site/markdown/index.md
  metricshub-doc/src/site/site.xml
Labels: developer_tested

#388 Issue #384: Remove Connector Design Guide from the documentation
  metricshub-doc/src/site/markdown/configuration/configure-monitoring.md
  metricshub-doc/src/site/markdown/develop/computes/add.md
  metricshub-doc/src/site/markdown/develop/computes/and.md
  metricshub-doc/src/site/markdown/develop/computes/append.md
  metricshub-doc/src/site/markdown/develop/computes/array-translate.md
  metricshub-doc/src/site/markdown/develop/computes/awk.md
  metricshub-doc/src/site/markdown/develop/computes/convert.md
  metricshub-doc/src/site/markdown/develop/computes/divide.md
  metricshub-doc/src/site/markdown/develop/computes/duplicate-column.md
  metricshub-doc/src/site/markdown/develop/computes/exclude-matching-lines.md
  metricshub-doc/src/site/markdown/develop/computes/extract-wbem-property.md
  metricshub-doc/src/site/markdown/develop/computes/extract.md
  metricshub-doc/src/site/markdown/develop/computes/index.md
  metricshub-doc/src/site/markdown/develop/computes/json2csv.md
  metricshub-doc/src/site/markdown/develop/computes/keep-columns.md
  metricshub-doc/src/site/markdown/develop/computes/keep-only-matching-lines.md
  metricshub-doc/src/site/markdown/develop/computes/multiply.md
  metricshub-doc/src/site/markdown/develop/computes/prepend.md
  metricshub-doc/src/site/markdown/develop/computes/replace.md
  metricshub-doc/src/site/markdown/develop/computes/substring.md
  metricshub-doc/src/site/markdown/develop/computes/subtract.md
  metricshub-doc/src/site/markdown/develop/computes/translate-per-bit.md
  metricshub-doc/src/site/markdown/develop/computes/translate.md
  metricshub-doc/src/site/markdown/develop/computes/xml2csv.md
  metricshub-doc/src/site/markdown/develop/connector.md
  metricshub-doc/src/site/markdown/develop/detection/command-line.md
  metricshub-doc/src/site/markdown/develop/detection/engine-requirements.md
  metricshub-doc/src/site/markdown/develop/detection/http.md
  metricshub-doc/src/site/markdown/develop/detection/index.md
  metricshub-doc/src/site/markdown/develop/detection/ipmi.md
  metricshub-doc/src/site/markdown/develop/detection/process.md
  metricshub-doc/src/site/markdown/develop/detection/resource-type.md
  metricshub-doc/src/site/markdown/develop/detection/service.md
  metricshub-doc/src/site/markdown/develop/detection/snmp-get.md
  metricshub-doc/src/site/markdown/develop/detection/snmp-getnext.md
  metricshub-doc/src/site/markdown/develop/detection/wbem.md
  metricshub-doc/src/site/markdown/develop/detection/wmi.md
  metricshub-doc/src/site/markdown/develop/index.md
  metricshub-doc/src/site/markdown/develop/monitors.md
  metricshub-doc/src/site/markdown/develop/references.md
  metricshub-doc/src/site/markdown/develop/sources/command-line.md
  metricshub-doc/src/site/markdown/develop/sources/copy.md
  metricshub-doc/src/site/markdown/develop/sources/http.md
  metricshub-doc/src/site/markdown/develop/sources/index.md
  metricshub-doc/src/site/markdown/develop/sources/ipmi.md
  metricshub-doc/src/site/markdown/develop/sources/pre.md
  metricshub-doc/src/site/markdown/develop/sources/snmp-get.md
  metricshub-doc/src/site/markdown/develop/sources/snmp-table.md
  metricshub-doc/src/site/markdown/develop/sources/sql.md
  metricshub-doc/src/site/markdown/develop/sources/static.md
  metricshub-doc/src/site/markdown/develop/sources/table-join.md
  metricshub-doc/src/site/markdown/develop/sources/table-union.md
  metricshub-doc/src/site/markdown/develop/sources/wbem.md
  metricshub-doc/src/site/markdown/develop/sources/wmi.md
  metricshub-doc/src/site/resources/images/connector-overview.png
  metricshub-doc/src/site/site.xml
Labels: developer_tested

#390 Issue #389: Link to MetricsHub Community Connectors 1.0.05
  pom.xml
Labels: dependencies

#391 Issue #372: Allow the user to override the path to the ./connectors subdirectory
  metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/config/AgentConfig.java
  metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/context/AgentContext.java
  metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/helper/ConfigHelper.java
  metricshub-agent/src/main/java/org/sentrysoftware/metricshub/cli/service/MetricsHubCliService.java
  metricshub-doc/src/site/markdown/configuration/configure-monitoring.md
  metricshub-doc/src/site/markdown/troubleshooting/cli.md
Labels: developer_tested

#395 Issue 394: Removed reference to Hardware Sentry Agent
  metricshub-doc/src/site/markdown/troubleshooting/status.md
Labels: documentation

#396 Issue 393: Data export topic is misleading
  metricshub-doc/src/site/markdown/configuration/send-telemetry.md
  metricshub-doc/src/site/site.xml
Labels: documentation

#400 Issue #399: Documentation review
  metricshub-doc/pom.xml
  metricshub-doc/src/site/markdown/guides/cli.md
  metricshub-doc/src/site/markdown/index.md
  metricshub-doc/src/site/markdown/install/debian-linux.md
  metricshub-doc/src/site/markdown/install/docker.md
  metricshub-doc/src/site/markdown/install/redhat-linux.md
  metricshub-doc/src/site/markdown/install/windows.md
Labels: developer_tested

#403 Issue #401: Report hw.network.bandwidth.limit in byte/s
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/utils/MappingProcessor.java
  metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/utils/MappingProcessorTest.java
  metricshub-hardware/src/it/resources/os/SuperConnectorOsIT/expected/expected.json
  metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/HardwareEnergyPostExecutionService.java
  metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/sustainability/NetworkPowerAndEnergyEstimator.java
  metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/util/HwCollectHelper.java
  metricshub-hardware/src/test/java/org/sentrysoftware/metricshub/hardware/sustainability/NetworkPowerAndEnergyEstimatorTest.java
  metricshub-oscommand-extension/src/it/resources/os/SuperConnectorOsIT/expected/expected.json
Labels: developer_tested

#404 Issue #399: Renamed Install to Installation in the documentation menu
  metricshub-doc/src/site/markdown/installation/debian-linux.md
  metricshub-doc/src/site/markdown/installation/docker.md
  metricshub-doc/src/site/markdown/installation/index.md
  metricshub-doc/src/site/markdown/installation/redhat-linux.md
  metricshub-doc/src/site/markdown/installation/windows.md
  metricshub-doc/src/site/site.xml
Labels: developer_tested

#409 Issue #383: Network Bandwidth requires a new method megaBit2Byte
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/utils/MappingProcessor.java
  metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/utils/MappingProcessorTest.java
  metricshub-hardware/src/it/resources/os/SuperConnectorOsIT/connectors/SuperConnectorCommon-header/SuperConnectorCommon-header.yaml
  metricshub-oscommand-extension/src/it/resources/os/SuperConnectorOsIT/connectors/SuperConnectorCommon-header/SuperConnectorCommon-header.yaml
Labels: developer_tested

#416 Issue #414: Link to MetricsHub Community Connectors 1.0.06
  pom.xml
Labels: developer_tested

#413 Issue #410: Shallow copy issue when managing multiple hosts in protocol configuration
  metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/config/ResourceConfig.java
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/configuration/IConfiguration.java
  metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/configuration/OsCommandTestConfiguration.java
  metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/extension/TestConfiguration.java
  metricshub-http-extension/src/main/java/org/sentrysoftware/metricshub/extension/http/HttpConfiguration.java
  metricshub-http-extension/src/test/java/org/sentrysoftware/metricshub/extension/http/HttpConfigurationTest.java
  metricshub-http-extension/src/test/java/org/sentrysoftware/metricshub/extension/http/HttpExtensionTest.java
  metricshub-ipmi-extension/src/main/java/org/sentrysoftware/metricshub/extension/ipmi/IpmiConfiguration.java
  metricshub-ipmi-extension/src/test/java/org/sentrysoftware/IpmiConfigurationTest.java
  metricshub-ipmi-extension/src/test/java/org/sentrysoftware/IpmiExtensionTest.java
  metricshub-oscommand-extension/src/main/java/org/sentrysoftware/metricshub/extension/oscommand/OsCommandConfiguration.java
  metricshub-oscommand-extension/src/main/java/org/sentrysoftware/metricshub/extension/oscommand/SshConfiguration.java
  metricshub-oscommand-extension/src/test/java/org/sentrysoftware/metricshub/extension/oscommand/OsCommandConfigurationTest.java
  metricshub-oscommand-extension/src/test/java/org/sentrysoftware/metricshub/extension/oscommand/OsCommandExtensionTest.java
  metricshub-oscommand-extension/src/test/java/org/sentrysoftware/metricshub/extension/oscommand/SshConfigurationTest.java
  metricshub-ping-extension/src/main/java/org/sentrysoftware/metricshub/extension/ping/PingConfiguration.java
  metricshub-ping-extension/src/test/java/org/sentrysoftware/metricshub/extension/ping/PingConfigurationTest.java
  metricshub-ping-extension/src/test/java/org/sentrysoftware/metricshub/extension/ping/PingExtensionTest.java
  metricshub-snmp-extension/src/main/java/org/sentrysoftware/metricshub/extension/snmp/SnmpConfiguration.java
  metricshub-snmp-extension/src/test/java/org/sentrysoftware/metricshub/extension/snmp/SnmpConfigurationTest.java
  metricshub-snmp-extension/src/test/java/org/sentrysoftware/metricshub/extension/snmp/SnmpExtensionTest.java
  metricshub-snmpv3-extension/src/main/java/org/sentrysoftware/metricshub/extension/snmpv3/SnmpV3Configuration.java
  metricshub-snmpv3-extension/src/test/java/org/sentrysoftware/metricshub/extension/snmpv3/SnmpV3ConfigurationTest.java
  metricshub-snmpv3-extension/src/test/java/org/sentrysoftware/metricshub/extension/snmpv3/SnmpV3ExtensionTest.java
  metricshub-wbem-extension/src/main/java/org/sentrysoftware/metricshub/extension/wbem/WbemConfiguration.java
  metricshub-wbem-extension/src/test/java/org/sentrysoftware/metricshub/extension/wbem/WbemConfigurationTest.java
  metricshub-wbem-extension/src/test/java/org/sentrysoftware/metricshub/extension/wbem/WbemExtensionTest.java
  metricshub-win-extension-common/src/test/java/org/sentrysoftware/metricshub/extension/win/WmiTestConfiguration.java
  metricshub-winrm-extension/src/main/java/org/sentrysoftware/metricshub/extension/winrm/WinRmConfiguration.java
  metricshub-winrm-extension/src/test/java/org/sentrysoftware/metricshub/extension/winrm/WinRmConfigurationTest.java
  metricshub-winrm-extension/src/test/java/org/sentrysoftware/metricshub/extension/winrm/WinRmExtensionTest.java
  metricshub-wmi-extension/src/main/java/org/sentrysoftware/metricshub/extension/wmi/WmiConfiguration.java
  metricshub-wmi-extension/src/test/java/org/sentrysoftware/metricshub/extension/wmi/WmiConfigurationTest.java
  metricshub-wmi-extension/src/test/java/org/sentrysoftware/metricshub/extension/wmi/WmiExtensionTest.java
Labels: developer_tested

#418 Issue #412: Remove hw.status metric from monitors having connectors without hardware tags
  metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/HardwareEnergyPostExecutionService.java
  metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/strategy/HardwarePostDiscoveryStrategy.java
  metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/util/HwCollectHelper.java
  metricshub-hardware/src/test/java/org/sentrysoftware/metricshub/hardware/strategy/HardwarePostDiscoveryStrategyTest.java
Labels: enhancement, java, developer_tested

#420 Issue #368: KM module: issues with the VM class
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/utils/MappingProcessor.java
  metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/utils/MappingProcessorTest.java
  metricshub-hardware/src/it/resources/os/SuperConnectorOsIT/expected/expected.json
  metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/sustainability/VmPowerAndEnergyEstimator.java
  metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/util/HwConstants.java
  metricshub-oscommand-extension/src/it/resources/os/SuperConnectorOsIT/expected/expected.json
Labels: developer_tested

#426 Issue #374: Add the possibility to add default connector variables
  metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/helper/ConfigHelper.java
  metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/helper/ConnectorTemplateLibraryParser.java
  metricshub-agent/src/test/java/org/sentrysoftware/metricshub/agent/helper/ConnectorTemplateLibraryParserTest.java
  metricshub-agent/src/test/resources/connectorTemplateLibraryParser/templateVariable.yaml
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/connector/model/identity/ConnectorDefaultVariable.java
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/connector/model/identity/ConnectorIdentity.java
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/connector/parser/ConnectorLibraryParser.java
  metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/connector/parser/TemplateVariableProcessorTest.java
  metricshub-engine/src/test/resources/test-files/connector/templateVariable/templateVariable.json
  metricshub-jawk-extension/src/main/java/org/sentrysoftware/metricshub/extension/jawk/MetricsHubExtensionForJawk.java
Labels: developer_tested

#425 Issue #421: Alert noise reduction on `hw.status{state="present"}`
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/common/helpers/KnownMonitorType.java
  metricshub-hardware/src/it/resources/os/SuperConnectorOsIT/expected/expected.json
  metricshub-hardware/src/it/resources/snmp/DellOpenManageIT/expected/expected.json
  metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/strategy/HardwarePostCollectStrategy.java
  metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/strategy/HardwarePostDiscoveryStrategy.java
  metricshub-hardware/src/test/java/org/sentrysoftware/metricshub/hardware/HardwareEnergyPostExecutionServiceTest.java
  metricshub-hardware/src/test/java/org/sentrysoftware/metricshub/hardware/strategy/HardwarePostCollectStrategyTest.java
  metricshub-hardware/src/test/java/org/sentrysoftware/metricshub/hardware/strategy/HardwarePostDiscoveryStrategyTest.java
  metricshub-hardware/src/test/java/org/sentrysoftware/metricshub/hardware/strategy/HardwareStrategyTest.java
  metricshub-hardware/src/test/java/org/sentrysoftware/metricshub/hardware/strategy/StrategyTestHelper.java
  metricshub-hardware/src/test/resources/Linux/Linux.yaml
  metricshub-hardware/src/test/resources/Linux/memory.awk
  metricshub-hardware/src/test/resources/Linux/network.awk
  metricshub-hardware/src/test/resources/strategy/collect/TestConnector.yaml
Labels: developer_tested

#429 Issue #417: Fix wrong Javadoc references
  metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/process/config/ProcessOutput.java
  metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/process/runtime/ProcessControl.java
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/connector/deserializer/custom/SqlTableDeserializer.java
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/source/SourceProcessor.java
  metricshub-jawk-extension/src/main/java/org/sentrysoftware/metricshub/extension/jawk/MetricsHubExtensionForJawk.java
  metricshub-snmp-extension-common/src/main/java/org/sentrysoftware/metricshub/extension/snmp/AbstractSnmpRequestExecutor.java
  metricshub-snmp-extension-common/src/main/java/org/sentrysoftware/metricshub/extension/snmp/detection/SnmpGetNextCriterionProcessor.java
  metricshub-win-extension-common/src/main/java/org/sentrysoftware/metricshub/extension/win/detection/WmiCriterionProcessor.java
Labels: java
