Repository MetricsHub/metricshub-community, pull requests merged in 2024-07, with the labels that each got.

#295 Issue 286: Moved content available in solving.md
  metricshub-doc/src/site/markdown/getting-started-linux.md
  metricshub-doc/src/site/markdown/getting-started-windows.md
  metricshub-doc/src/site/markdown/troubleshooting/solving.md
  metricshub-doc/src/site/site.xml
Labels: documentation

#294 Issue #284: Renamed the getting started file names
  metricshub-doc/src/site/markdown/quick-start-community-prometheus-linux.md
  metricshub-doc/src/site/markdown/quick-start-community-prometheus-windows.md
  metricshub-doc/src/site/site.xml
Labels: documentation

#310 Issue #282: Rewrite the Overview page
  metricshub-doc/src/site/markdown/concepts.md
  metricshub-doc/src/site/markdown/index.md
  metricshub-doc/src/site/resources/images/otel-metricshub.png
  metricshub-doc/src/site/site.xml
Labels: documentation

#329 Issue #214: Document the hardware extension
  metricshub-doc/src/site/markdown/sustainability/configure-hardware-extension.md
  metricshub-doc/src/site/site.xml
Labels: documentation

#332 Issue #288: Review the user doc structure
  metricshub-doc/src/site/site.xml
Labels: documentation

#334 Issue #333: Fix Improper Default Right Line Interpretation
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/source/SourceProcessor.java
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/source/compute/ComputeProcessor.java
  metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/source/SourceProcessorTest.java
Labels: bug, java

#344 Issue #338: Update Hardware Extension Document Title for Better Clarity
  metricshub-doc/src/site/markdown/sustainability/configure-sustainability-metrics.md
  metricshub-doc/src/site/site.xml
Labels: developer_tested

#346 Issue #345: Update Key Components of a Connector Illustration
  metricshub-doc/src/site/resources/images/connector-overview.png
Labels: developer_tested

#348 Issue #272: Replace all telemetryManager.getHostConfiguration().getHostname() occurrences
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/client/ClientsExecutor.java
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/AbstractAllAtOnceStrategy.java
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/collect/CollectStrategy.java
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/detection/CriterionProcessor.java
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/source/SourceProcessor.java
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/source/SourceUpdaterProcessor.java
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/utils/ForceSerializationHelper.java
  metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/detection/CriterionProcessorTest.java
  metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/util/HwCollectHelper.java
  metricshub-oscommand-extension/src/main/java/org/sentrysoftware/metricshub/extension/oscommand/CommandLineSourceProcessor.java
Labels: developer_tested

#349 Issue #347: Improve clarity in MetricsHub sustainability settings documentation
  metricshub-doc/src/site/markdown/configuration/configure-monitoring.md
  metricshub-doc/src/site/markdown/sustainability/configure-sustainability-metrics.md
Labels: documentation, developer_tested

#351 Issue #350: Use MetricsHub Connector Maven Plugin `1.5.00`
  metricshub-doc/pom.xml
  metricshub-doc/src/site/resources/css/site.css
  metricshub-doc/src/site/site.xml
Labels: enhancement, developer_tested
