Repository MetricsHub/metricshub-community, pull requests merged in 2024-10, with the labels that each got.

#434 Issue #433: [BREAKING_CHANGE] Disable automatic Hostname to FQDN resolution
  metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/config/AgentConfig.java
  metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/helper/ConfigHelper.java
  metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/helper/OtelHelper.java
  metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/service/task/MonitoringTask.java
  metricshub-agent/src/main/java/org/sentrysoftware/metricshub/cli/service/MetricsHubCliService.java
  metricshub-agent/src/main/java/org/sentrysoftware/metricshub/cli/service/PrettyPrinterService.java
  metricshub-agent/src/test/java/org/sentrysoftware/metricshub/agent/helper/OtelHelperTest.java
  metricshub-agent/src/test/java/org/sentrysoftware/metricshub/agent/service/task/MonitoringTaskTest.java
  metricshub-agent/src/test/java/org/sentrysoftware/metricshub/cli/service/PrettyPrinterServiceTest.java
  metricshub-doc/src/site/markdown/configuration/configure-monitoring.md
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/configuration/HostConfiguration.java
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/telemetry/MonitorFactory.java
  metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/configuration/HostConfigurationTest.java
  metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/constants/Constants.java
  metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/detection/AutomaticDetectionTest.java
  metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/detection/CriterionProcessorTest.java
  metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/telemetry/MonitorFactoryTest.java
Labels: breaking_changes

#431 Issue #427: Add status information to connector monitor
  metricshub-agent/src/main/java/org/sentrysoftware/metricshub/cli/service/PrettyPrinterService.java
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/connector/model/identity/criterion/DeviceTypeCriterion.java
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/connector/model/identity/criterion/HttpCriterion.java
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/connector/model/identity/criterion/ProcessCriterion.java
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/connector/model/identity/criterion/ProductRequirementsCriterion.java
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/connector/model/identity/criterion/SnmpCriterion.java
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/connector/model/identity/criterion/SnmpGetCriterion.java
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/connector/model/identity/criterion/SnmpGetNextCriterion.java
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/AbstractStrategy.java
  metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/collect/CollectStrategyTest.java
  metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/discovery/DiscoveryStrategyTest.java
  metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/simple/SimpleStrategyTest.java
Labels: enhancement, java

#440 Issue #439: Connector default variables are not serializable
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/connector/model/identity/ConnectorDefaultVariable.java
Labels: developer_tested

#442 Issue #441: Removed resourcedetection from the documentation
  metricshub-doc/src/site/markdown/configuration/send-telemetry.md
  metricshub-doc/src/site/markdown/guides/status.md
Labels: documentation

#443 Issue #422: Rename SQL Source Module to localSql Source
  README.md
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/connector/model/monitor/task/source/LocalSqlSource.java
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/connector/model/monitor/task/source/Source.java
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/source/ISourceProcessor.java
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/source/SourceProcessor.java
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/source/SourceUpdaterProcessor.java
  metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/connector/deserializer/source/LocalSqlSourceDeserializerTest.java
  metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/source/SourceProcessorTest.java
  metricshub-engine/src/test/resources/test-files/source/sql/localSqlSource.yaml
  metricshub-linux/pom.xml
  metricshub-localsql-source-extension/pom.xml
  metricshub-localsql-source-extension/src/main/java/lombok.config
  metricshub-localsql-source-extension/src/main/java/org/sentrysoftware/metricshub/extension/sql/LocalSqlExtension.java
  metricshub-localsql-source-extension/src/main/java/org/sentrysoftware/metricshub/extension/sql/SqlClientExecutor.java
  metricshub-localsql-source-extension/src/main/resources/META-INF/services/org.sentrysoftware.metricshub.engine.extension.ISourceComputationExtension
  metricshub-localsql-source-extension/src/test/java/org/sentrysoftware/metricshub/extension/sql/LocalSqlExtensionTest.java
  metricshub-localsql-source-extension/src/test/java/org/sentrysoftware/metricshub/extension/sql/SqlClientExecutorTest.java
  metricshub-sql-source-extension/src/main/resources/META-INF/services/org.sentrysoftware.metricshub.engine.extension.ISourceComputationExtension
  metricshub-windows/pom.xml
  pom.xml
Labels: developer_tested

#449 Issue #448: Document MetricsHub Enterprise upgrade procedure
  metricshub-doc/src/site/markdown/installation/debian-linux.md
  metricshub-doc/src/site/markdown/installation/docker.md
  metricshub-doc/src/site/markdown/installation/redhat-linux.md
  metricshub-doc/src/site/markdown/installation/windows.md
Labels: documentation

#454 Issue #455: Update ESXi configuration example in `metricshub-example.yaml`
  metricshub-linux/src/main/resources/jpackage/metricshub/config/metricshub-example.yaml
  metricshub-windows/src/main/resources/jpackage/MetricsHub/config/metricshub-example.yaml
Labels: enhancement

#458 Issue #456: Fix missing dom4j dependency in the WBEM extension
  metricshub-wbem-extension/pom.xml
  metricshub-wbem-extension/src/main/java/org/sentrysoftware/metricshub/extension/wbem/WbemRequestExecutor.java
Labels: bug, developer_tested

#445 Issue #444: Write the release notes
  metricshub-doc/src/site/markdown/release-notes.md
  metricshub-doc/src/site/site.xml
Labels: documentation, developer_tested

#464 Issue #461: Move cli.md to the Appendix section
  metricshub-doc/src/site/markdown/appendix/cli.md
  metricshub-doc/src/site/site.xml
Labels: documentation

#453 Issue #432: Standardize the messages for all the criteria tests
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/AbstractStrategy.java
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/detection/CriterionProcessor.java
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/detection/CriterionTestResult.java
  metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/collect/CollectStrategyTest.java
  metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/detection/CriterionProcessorTest.java
  metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/discovery/DiscoveryStrategyTest.java
  metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/simple/SimpleStrategyTest.java
Labels: developer_tested

#430 Issue #379: Add support for escaped macros
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/common/helpers/EscapeType.java
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/common/helpers/MacroType.java
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/common/helpers/MacrosUpdater.java
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/common/helpers/MetricsHubConstants.java
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/common/helpers/StringHelper.java
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/utils/OsCommandHelper.java
  metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/common/helpers/MacrosUpdaterTest.java
  metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/common/helpers/StringHelperTest.java
  metricshub-http-extension/src/main/java/org/sentrysoftware/metricshub/extension/http/HttpRequestExecutor.java
  metricshub-http-extension/src/main/java/org/sentrysoftware/metricshub/extension/http/utils/EmbeddedFileBody.java
  metricshub-http-extension/src/main/java/org/sentrysoftware/metricshub/extension/http/utils/Header.java
  metricshub-http-extension/src/main/java/org/sentrysoftware/metricshub/extension/http/utils/HttpMacrosUpdater.java
  metricshub-http-extension/src/main/java/org/sentrysoftware/metricshub/extension/http/utils/StringBody.java
  metricshub-http-extension/src/main/java/org/sentrysoftware/metricshub/extension/http/utils/UrlHelper.java
  metricshub-http-extension/src/test/java/org/sentrysoftware/metricshub/extension/http/utils/HttpMacrosUpdaterTest.java
  metricshub-oscommand-extension/src/main/java/org/sentrysoftware/metricshub/extension/oscommand/OsCommandRequestExecutor.java
  metricshub-oscommand-extension/src/main/java/org/sentrysoftware/metricshub/extension/oscommand/OsCommandService.java
  metricshub-oscommand-extension/src/test/java/org/sentrysoftware/metricshub/extension/oscommand/OsCommandExtensionTest.java
  metricshub-oscommand-extension/src/test/java/org/sentrysoftware/metricshub/extension/oscommand/OsCommandHelperTest.java
  metricshub-win-extension-common/pom.xml
  metricshub-win-extension-common/src/main/java/org/sentrysoftware/metricshub/extension/win/WinCommandService.java
  metricshub-win-extension-common/src/test/java/org/sentrysoftware/metricshub/extension/win/WinCommandServiceTest.java
Labels: enhancement, java

#466 Issue #462 Review configure-monitoring.md
  metricshub-doc/src/site/markdown/configuration/configure-monitoring.md
  metricshub-doc/src/site/markdown/guides/configure-sustainability-metrics.md
Labels: documentation

#469 Issue #468: Support shared-characteristics for centralized resources
  metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/deserialization/PostConfigDeserializer.java
Labels: enhancement, developer_tested

#473 Issue #472: Prevent sensitive configuration details from being displayed in error logs
  metricshub-http-extension/src/main/java/org/sentrysoftware/metricshub/extension/http/HttpExtension.java
  metricshub-ipmi-extension/src/main/java/org/sentrysoftware/metricshub/extension/ipmi/IpmiExtension.java
  metricshub-oscommand-extension/src/main/java/org/sentrysoftware/metricshub/extension/oscommand/OsCommandExtension.java
  metricshub-ping-extension/src/main/java/org/sentrysoftware/metricshub/extension/ping/PingExtension.java
  metricshub-snmp-extension/src/main/java/org/sentrysoftware/metricshub/extension/snmp/SnmpExtension.java
  metricshub-snmpv3-extension/src/main/java/org/sentrysoftware/metricshub/extension/snmpv3/SnmpV3Extension.java
  metricshub-wbem-extension/src/main/java/org/sentrysoftware/metricshub/extension/wbem/WbemExtension.java
  metricshub-winrm-extension/src/main/java/org/sentrysoftware/metricshub/extension/winrm/WinRmExtension.java
  metricshub-wmi-extension/src/main/java/org/sentrysoftware/metricshub/extension/wmi/WmiExtension.java
Labels: developer_tested
