Repository MetricsHub/metricshub-community, pull requests merged in 2024-12, with the labels that each got.

#507 Issue #465: Add job duration metric for monitor jobs
  metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/service/signal/AbstractNumberMetricObserver.java
  metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/service/task/MonitoringTask.java
  metricshub-agent/src/main/resources/metricshub-host-metrics.yaml
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/AbstractAllAtOnceStrategy.java
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/AbstractStrategy.java
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/collect/CollectStrategy.java
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/surrounding/SurroundingStrategy.java
  metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/collect/CollectStrategyTest.java
  metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/discovery/DiscoveryStrategyTest.java
  metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/simple/SimpleStrategyTest.java
  metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/surrounding/AfterAllStrategyTest.java
  metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/surrounding/BeforeAllStrategyTest.java
Labels: enhancement, developer_tested

#506 Issue #505: Update references to logging exporter
  metricshub-doc/src/site/markdown/configuration/send-telemetry.md
Labels: documentation

#513 Issue #512: Prepare MetricsHub Release
  metricshub-doc/pom.xml
  pom.xml
Labels: dependencies

#522 Issue #518: Enable job duration metric reporting through MetricsHub configuration
  metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/config/AgentConfig.java
  metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/config/ResourceConfig.java
  metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/config/ResourceGroupConfig.java
  metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/helper/ConfigHelper.java
  metricshub-agent/src/test/java/org/sentrysoftware/metricshub/agent/helper/ConfigHelperTest.java
  metricshub-agent/src/test/resources/config/metricshub-enable-self-monitoring-no-config.yaml
  metricshub-agent/src/test/resources/config/metricshub-enable-self-monitoring-override.yaml
  metricshub-agent/src/test/resources/config/metricshub.yaml
  metricshub-agent/src/test/resources/config/top-level-resource-test.yaml
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/configuration/HostConfiguration.java
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/AbstractStrategy.java
  metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/AbstractStrategyTest.java
  metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/collect/CollectStrategyTest.java
  metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/simple/SimpleStrategyTest.java
Labels: enhancement, developer_tested

#524 Issue #523: hw.network.up metric not reported for WARN or ALARM states
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/common/helpers/state/LinkStatus.java
  metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/common/helpers/state/LinkStatusTest.java
Labels: developer_tested
