Repository MetricsHub/metricshub-community, pull requests merged in 2024-08, with the labels that each got.

#354 Issue #353: Updated maven link in the requirements section of `README.md`
  README.md
Labels: documentation

#356 Issue #317: Feature Request: Add $index Directive to Collect Row Number in Metric attribute
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/AbstractAllAtOnceStrategy.java
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/collect/CollectStrategy.java
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/utils/MappingProcessor.java
  metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/utils/MappingProcessorTest.java
  metricshub-hardware/src/it/resources/os/SuperConnectorOsIT/connectors/SuperConnectorCommon-header/SuperConnectorCommon-header.yaml
  metricshub-hardware/src/it/resources/os/SuperConnectorOsIT/expected/expected.json
Labels: developer_tested

#360 Issue #352: Exclude non hardware items from power estimation
  metricshub-hardware/src/it/resources/os/SuperConnectorOsIT/connectors/SuperConnectorOS/SuperConnectorOS.yaml
  metricshub-hardware/src/it/resources/snmp/DellOpenManageIT/connectors/DellOpenManage/DellOpenManage.yaml
  metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/HardwareEnergyPostExecutionService.java
  metricshub-hardware/src/test/java/org/sentrysoftware/metricshub/hardware/HardwareEnergyPostExecutionServiceTest.java
  metricshub-hardware/src/test/java/org/sentrysoftware/metricshub/hardware/strategy/HardwareStrategyTest.java
  metricshub-hardware/src/test/resources/Linux/Linux.yaml
  metricshub-hardware/src/test/resources/Linux/memory.awk
  metricshub-hardware/src/test/resources/Linux/network.awk
  metricshub-hardware/src/test/resources/strategy/collect/TestConnector.yaml
Labels: bug, developer_tested

#359 Issue #358: Update Documentation: Docker.md for Enterprise Edition
  metricshub-doc/src/site/markdown/install/docker.md
Labels: developer_tested

#361 Issue #355: Added support for `%{PASSWORD_JSON}` and `%{USERNAME_JSON}`
  metricshub-http-extension/src/main/java/org/sentrysoftware/metricshub/extension/http/utils/HttpMacrosUpdater.java
  metricshub-http-extension/src/test/java/org/sentrysoftware/metricshub/extension/http/utils/HttpMacrosUpdaterTest.java
Labels: developer_tested

#364 Issue #363: Handle null or empty source table by setting it to an empty
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/AbstractStrategy.java
Labels: developer_tested

#367 Issue #366: Recognize '2c' as a valid SNMP version option
  metricshub-snmp-extension/src/main/java/org/sentrysoftware/metricshub/extension/snmp/SnmpConfiguration.java
  metricshub-snmp-extension/src/test/java/org/sentrysoftware/metricshub/extension/snmp/SnmpConfigurationTest.java
Labels: developer_tested

#377 Issue #297: Manage WMI Empty Username
  metricshub-wmi-extension/pom.xml
  metricshub-wmi-extension/src/main/java/org/sentrysoftware/metricshub/extension/wmi/WmiRequestExecutor.java
Labels: developer_tested
