Repository MetricsHub/metricshub-community, pull requests merged in 2025-06, with the labels that each got.

#695 Issue #693: Fix monitor names that are generated for non-Hardware monitors
  metricshub-agent/src/main/java/org/metricshub/agent/service/task/MonitoringTask.java
  metricshub-agent/src/test/java/org/metricshub/agent/service/task/MonitoringTaskTest.java
  metricshub-hardware/src/main/java/org/metricshub/hardware/strategy/HardwareMonitorNameGenerationStrategy.java
  metricshub-hardware/src/main/java/org/metricshub/hardware/strategy/HardwarePostDiscoveryStrategy.java
  metricshub-hardware/src/test/java/org/metricshub/hardware/strategy/HardwareMonitorNameGenerationStrategyTest.java
Labels: bug

#706 Issue #703: Fix NumberFormatException error during Hex to number conversion
  metricshub-engine/src/main/java/org/metricshub/engine/strategy/source/compute/ComputeProcessor.java
  metricshub-engine/src/test/java/org/metricshub/engine/strategy/source/compute/ComputeProcessorTest.java
Labels: bug

#689 Issue #684: Document custom monitoring examples
  metricshub-doc/src/site/markdown/custom/index.md
  metricshub-doc/src/site/markdown/custom/linux-process.md
  metricshub-doc/src/site/markdown/custom/linux-service.md
  metricshub-doc/src/site/markdown/custom/snmp-polling.md
  metricshub-doc/src/site/markdown/custom/web-request.md
  metricshub-doc/src/site/markdown/custom/windows-process.md
  metricshub-doc/src/site/markdown/custom/windows-service.md
  metricshub-doc/src/site/site.xml
Labels: documentation

#709 Issue #708 Fix the SchemaStore Link
  metricshub-doc/src/site/markdown/configuration/configure-monitoring.md
  metricshub-doc/src/site/markdown/configuration/send-telemetry.md
Labels: documentation

#707 Issue #692: Create MetricsHub Server with REST API and Remote MCP support
  metricshub-agent/pom.xml
  metricshub-agent/src/main/java/org/metricshub/agent/MetricsHubAgentApplication.java
  metricshub-agent/src/main/java/org/metricshub/agent/config/AgentConfig.java
  metricshub-agent/src/main/java/org/metricshub/agent/process/runtime/AbstractProcess.java
  metricshub-agent/src/main/java/org/metricshub/web/AgentContextHolder.java
  metricshub-agent/src/main/java/org/metricshub/web/MetricsHubAgentServer.java
  metricshub-agent/src/main/java/org/metricshub/web/config/ToolCallbackConfiguration.java
  metricshub-agent/src/main/java/org/metricshub/web/controller/ApplicationStatusController.java
  metricshub-agent/src/main/java/org/metricshub/web/dto/ApplicationStatus.java
  metricshub-agent/src/main/java/org/metricshub/web/mcp/PingResponse.java
  metricshub-agent/src/main/java/org/metricshub/web/mcp/PingToolService.java
  metricshub-agent/src/main/java/org/metricshub/web/service/ApplicationStatusService.java
  metricshub-agent/src/main/resources/application.yaml
  metricshub-agent/src/main/resources/log4j2.xml
  metricshub-agent/src/test/java/org/metricshub/agent/process/runtime/AbstractProcessTest.java
  metricshub-agent/src/test/java/org/metricshub/agent/service/OtelCollectorProcessServiceTest.java
  metricshub-agent/src/test/java/org/metricshub/web/config/ToolCallbackConfigurationTest.java
  metricshub-agent/src/test/java/org/metricshub/web/controller/ApplicationStatusControllerTest.java
  metricshub-agent/src/test/java/org/metricshub/web/mcp/PingToolServiceTest.java
  metricshub-agent/src/test/java/org/metricshub/web/service/ApplicationStatusServiceTest.java
  metricshub-doc/src/site/markdown/integrations/ai-agent-mcp.md
  metricshub-doc/src/site/resources/images/metricshub-mcp-openai.png
  metricshub-doc/src/site/site.xml
  pom.xml
Labels: documentation, developer-tested

#712 Issue #702: Document execute custom SQL queries
  metricshub-doc/src/site/markdown/custom/database-query.md
  metricshub-doc/src/site/markdown/custom/linux-process.md
  metricshub-doc/src/site/markdown/custom/linux-service.md
  metricshub-doc/src/site/markdown/custom/snmp-polling.md
  metricshub-doc/src/site/markdown/custom/web-request.md
  metricshub-doc/src/site/markdown/custom/windows-process.md
  metricshub-doc/src/site/markdown/custom/windows-service.md
  metricshub-doc/src/site/site.xml
Labels: documentation, developer-tested

#727 Issue #717: Release notes for MetricsHub v2.1.00
  metricshub-doc/pom.xml
  metricshub-doc/src/site/markdown/custom/index.md
  metricshub-doc/src/site/markdown/release-notes.md
  pom.xml
Labels: developer-tested
