Repository MetricsHub/metricshub-community, pull requests merged in 2025-01, with the labels that each got.

#531 Issue #529: Create a troubleshooting section
  metricshub-doc/src/site/markdown/troubleshooting/index.md
  metricshub-doc/src/site/markdown/troubleshooting/metricshub-logs.md
  metricshub-doc/src/site/markdown/troubleshooting/no-data-observability-platforms.md
  metricshub-doc/src/site/markdown/troubleshooting/no-data-resources.md
  metricshub-doc/src/site/markdown/troubleshooting/otel-logs.md
  metricshub-doc/src/site/site.xml
Labels: documentation

#528 Issue #525: Add job duration metrics to connectors
  metricshub-doc/src/site/markdown/configuration/configure-monitoring.md
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/connector/model/Connector.java
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/AbstractAllAtOnceStrategy.java
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/AbstractStrategy.java
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/collect/CollectStrategy.java
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/surrounding/SurroundingStrategy.java
  metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/AbstractStrategyTest.java
  metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/collect/CollectStrategyTest.java
  metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/discovery/DiscoveryStrategyTest.java
  metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/simple/SimpleStrategyTest.java
  metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/surrounding/AfterAllStrategyTest.java
  metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/surrounding/BeforeAllStrategyTest.java
Labels: documentation, enhancement

#532 Issue #521: Update OpenTelemetry dependencies to version 1.45.0
  pom.xml
Labels: developer_tested

#542 Issue #541: Remove use cases
  metricshub-doc/src/site/markdown/configuration/configure-monitoring.md
  metricshub-doc/src/site/markdown/usecases/network-interfaces.md
  metricshub-doc/src/site/markdown/usecases/ping.md
  metricshub-doc/src/site/markdown/usecases/process-windows.md
  metricshub-doc/src/site/markdown/usecases/remote-linux.md
  metricshub-doc/src/site/markdown/usecases/service-health.md
  metricshub-doc/src/site/markdown/usecases/service-linux.md
  metricshub-doc/src/site/site.xml
Labels: documentation

#540 Issue #526: Document Protocol CLIs
  metricshub-doc/src/site/markdown/appendix/cli.md
  metricshub-doc/src/site/markdown/troubleshooting/cli/http.md
  metricshub-doc/src/site/markdown/troubleshooting/cli/index.md
  metricshub-doc/src/site/markdown/troubleshooting/cli/ipmi.md
  metricshub-doc/src/site/markdown/troubleshooting/cli/jdbc.md
  metricshub-doc/src/site/markdown/troubleshooting/cli/ping.md
  metricshub-doc/src/site/markdown/troubleshooting/cli/snmp.md
  metricshub-doc/src/site/markdown/troubleshooting/cli/snmpv3.md
  metricshub-doc/src/site/markdown/troubleshooting/cli/ssh.md
  metricshub-doc/src/site/markdown/troubleshooting/cli/wbem.md
  metricshub-doc/src/site/markdown/troubleshooting/cli/winrm.md
  metricshub-doc/src/site/markdown/troubleshooting/cli/wmi.md
  metricshub-doc/src/site/markdown/troubleshooting/no-data-resources.md
  metricshub-doc/src/site/site.xml
Labels: developer_tested

#550 Issue #543: Add suffix cli to the Protocol CLI executables
  metricshub-agent/src/main/java/org/sentrysoftware/metricshub/cli/HttpCli.java
  metricshub-agent/src/main/java/org/sentrysoftware/metricshub/cli/IpmiCli.java
  metricshub-agent/src/main/java/org/sentrysoftware/metricshub/cli/JdbcCli.java
  metricshub-agent/src/main/java/org/sentrysoftware/metricshub/cli/PingCli.java
  metricshub-agent/src/main/java/org/sentrysoftware/metricshub/cli/SnmpCli.java
  metricshub-agent/src/main/java/org/sentrysoftware/metricshub/cli/SnmpV3Cli.java
  metricshub-agent/src/main/java/org/sentrysoftware/metricshub/cli/SshCli.java
  metricshub-agent/src/main/java/org/sentrysoftware/metricshub/cli/WbemCli.java
  metricshub-agent/src/main/java/org/sentrysoftware/metricshub/cli/WinRmCli.java
  metricshub-agent/src/main/java/org/sentrysoftware/metricshub/cli/WmiCli.java
  metricshub-doc/src/site/markdown/troubleshooting/cli/http.md
  metricshub-doc/src/site/markdown/troubleshooting/cli/index.md
  metricshub-doc/src/site/markdown/troubleshooting/cli/ipmi.md
  metricshub-doc/src/site/markdown/troubleshooting/cli/jdbc.md
  metricshub-doc/src/site/markdown/troubleshooting/cli/ping.md
  metricshub-doc/src/site/markdown/troubleshooting/cli/snmp.md
  metricshub-doc/src/site/markdown/troubleshooting/cli/snmpv3.md
  metricshub-doc/src/site/markdown/troubleshooting/cli/ssh.md
  metricshub-doc/src/site/markdown/troubleshooting/cli/wbem.md
  metricshub-doc/src/site/markdown/troubleshooting/cli/winrm.md
  metricshub-doc/src/site/markdown/troubleshooting/cli/wmi.md
  metricshub-linux/pom.xml
  metricshub-linux/src/main/resources/jpackage/metricshub-httpcli.properties
  metricshub-linux/src/main/resources/jpackage/metricshub-ipmicli.properties
  metricshub-linux/src/main/resources/jpackage/metricshub-jdbccli.properties
  metricshub-linux/src/main/resources/jpackage/metricshub-pingcli.properties
  metricshub-linux/src/main/resources/jpackage/metricshub-snmpcli.properties
  metricshub-linux/src/main/resources/jpackage/metricshub-snmpv3cli.properties
  metricshub-linux/src/main/resources/jpackage/metricshub-sshcli.properties
  metricshub-linux/src/main/resources/jpackage/metricshub-wbemcli.properties
  metricshub-linux/src/main/resources/jpackage/metricshub-winrmcli.properties
  metricshub-linux/src/main/resources/jpackage/metricshub-wmicli.properties
  metricshub-windows/pom.xml
  metricshub-windows/src/main/resources/jpackage/metricshub-httpcli.properties
  metricshub-windows/src/main/resources/jpackage/metricshub-ipmicli.properties
  metricshub-windows/src/main/resources/jpackage/metricshub-jdbccli.properties
  metricshub-windows/src/main/resources/jpackage/metricshub-pingcli.properties
  metricshub-windows/src/main/resources/jpackage/metricshub-snmpcli.properties
  metricshub-windows/src/main/resources/jpackage/metricshub-snmpv3cli.properties
  metricshub-windows/src/main/resources/jpackage/metricshub-sshcli.properties
  metricshub-windows/src/main/resources/jpackage/metricshub-wbemcli.properties
  metricshub-windows/src/main/resources/jpackage/metricshub-winrmcli.properties
  metricshub-windows/src/main/resources/jpackage/metricshub-wmicli.properties
Labels: documentation, enhancement, no_release_notes

#556 Issue #555: Prepare MetricsHub Release
  metricshub-doc/pom.xml
  pom.xml
Labels: dependencies

#562 Issue #561
  metricshub-doc/src/site/site.xml
Labels: documentation

#564 Issue #563: Make commits manual and optimize insert queries
  metricshub-internaldb-extension/src/main/java/org/sentrysoftware/metricshub/extension/internaldb/ColumnMetadata.java
  metricshub-internaldb-extension/src/main/java/org/sentrysoftware/metricshub/extension/internaldb/DatabaseHelper.java
  metricshub-internaldb-extension/src/main/java/org/sentrysoftware/metricshub/extension/internaldb/SqlClientExecutor.java
  metricshub-internaldb-extension/src/test/java/org/sentrysoftware/metricshub/extension/internaldb/SqlClientExecutorTest.java
  pom.xml
Labels: developer_tested

#566 Issue #565: Prepare MetricsHub Release 1.0.01
  metricshub-doc/src/site/markdown/release-notes.md
Labels: developer_tested

#568 Issue #567: Added unit tests to metricshub-internaldb-extension
  metricshub-internaldb-extension/pom.xml
  metricshub-internaldb-extension/src/main/java/org/sentrysoftware/metricshub/extension/internaldb/DatabaseHelper.java
  metricshub-internaldb-extension/src/test/java/org/sentrysoftware/metricshub/extension/internaldb/DatabaseHelperTest.java
Labels: developer_tested
