Repository MetricsHub/metricshub-community, pull requests merged in 2025-02, with the labels that each got.

#579 Issue #577: IPMI Command processing fail with ArrayIndexOutOfBoundsException
  metricshub-oscommand-extension/src/main/java/org/sentrysoftware/metricshub/extension/oscommand/ipmi/IpmiHelper.java
Labels: developer_tested

#578 Issue #572: httpcli fails with NullPointerException
  metricshub-agent/src/main/java/org/sentrysoftware/metricshub/cli/HttpCli.java
  metricshub-agent/src/main/java/org/sentrysoftware/metricshub/cli/WmiCli.java
Labels: developer_tested

#581 Issue #580: Incorrect snmpv3cli flag (--retryIntervals instead of --retry)
  metricshub-agent/src/main/java/org/sentrysoftware/metricshub/cli/SnmpV3Cli.java
Labels: developer_tested

#585 Issue #576: Support IPMI-Over-LAN SHA-256 and MD5 authentication algorithms
  pom.xml
Labels: developer_tested

#591 Issue #590: `hw_voltage_limit_volts` is incorrectly collected
  metricshub-agent/src/main/dist/config/metricshub-alertmanager-rules-example.yaml
  metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/threshold/VoltageMetricNormalizer.java
  metricshub-hardware/src/test/java/org/sentrysoftware/metricshub/hardware/threshold/VoltageMetricNormalizerTest.java
Labels: bug, developer_tested

#598 Issue #597: Rename host response time to `metricshub.host.response_time`
  metricshub-agent/src/main/resources/metricshub-host-metrics.yaml
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/collect/ProtocolHealthCheckStrategy.java
  metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/collect/ProtocolHealthCheckStrategyTest.java
Labels: developer_tested

#600 Issue #582: Simplify the options required in httpcli
  metricshub-agent/src/main/java/org/sentrysoftware/metricshub/cli/HttpCli.java
  metricshub-agent/src/test/java/org/sentrysoftware/metricshub/cli/HttpCliTest.java
  metricshub-doc/src/site/markdown/troubleshooting/cli/http.md
Labels: developer_tested

#602 Issue #574: When upgrading from previous version
  metricshub-linux/pom.xml
  metricshub-windows/pom.xml
Labels: developer_tested

#606 Issue #605: Incorrect JAR Name Preventing MetricsHub from Starting
  metricshub-linux/src/main/resources/jpackage/jpackage.txt
  metricshub-linux/src/main/resources/jpackage/metricshub-agent.properties
  metricshub-linux/src/main/resources/jpackage/metricshub-encrypt.properties
  metricshub-linux/src/main/resources/jpackage/metricshub-httpcli.properties
  metricshub-linux/src/main/resources/jpackage/metricshub-ipmicli.properties
  metricshub-linux/src/main/resources/jpackage/metricshub-jdbccli.properties
  metricshub-linux/src/main/resources/jpackage/metricshub-pingcli.properties
  metricshub-linux/src/main/resources/jpackage/metricshub-snmpcli.properties
  metricshub-linux/src/main/resources/jpackage/metricshub-snmpv3cli.properties
  metricshub-linux/src/main/resources/jpackage/metricshub-sshcli.properties
  metricshub-linux/src/main/resources/jpackage/metricshub-wbemcli.properties
  metricshub-linux/src/main/resources/jpackage/metricshub-winrmcli.properties
  metricshub-linux/src/main/resources/jpackage/metricshub-wmicli.properties
  metricshub-windows/src/main/resources/jpackage/jpackage.txt
  metricshub-windows/src/main/resources/jpackage/metricshub-agent.properties
  metricshub-windows/src/main/resources/jpackage/metricshub-encrypt.properties
  metricshub-windows/src/main/resources/jpackage/metricshub-httpcli.properties
  metricshub-windows/src/main/resources/jpackage/metricshub-ipmicli.properties
  metricshub-windows/src/main/resources/jpackage/metricshub-jdbccli.properties
  metricshub-windows/src/main/resources/jpackage/metricshub-pingcli.properties
  metricshub-windows/src/main/resources/jpackage/metricshub-snmpcli.properties
  metricshub-windows/src/main/resources/jpackage/metricshub-snmpv3cli.properties
  metricshub-windows/src/main/resources/jpackage/metricshub-sshcli.properties
  metricshub-windows/src/main/resources/jpackage/metricshub-wbemcli.properties
  metricshub-windows/src/main/resources/jpackage/metricshub-winrmcli.properties
  metricshub-windows/src/main/resources/jpackage/metricshub-wmicli.properties
Labels: bug, developer_tested

#601 Issue #575: Support snmp v3 HMAC sha2 auth protocols
  metricshub-agent/src/main/java/org/sentrysoftware/metricshub/cli/SnmpV3Cli.java
  metricshub-agent/src/main/java/org/sentrysoftware/metricshub/cli/service/protocol/SnmpV3ConfigCli.java
  metricshub-doc/src/site/markdown/configuration/configure-monitoring.md
  metricshub-doc/src/site/markdown/troubleshooting/cli/snmpv3.md
  metricshub-linux/src/main/resources/jpackage/metricshub/config/metricshub-example.yaml
  metricshub-snmpv3-extension/src/main/java/org/sentrysoftware/metricshub/extension/snmpv3/SnmpV3Configuration.java
  metricshub-snmpv3-extension/src/main/java/org/sentrysoftware/metricshub/extension/snmpv3/SnmpV3RequestExecutor.java
  metricshub-snmpv3-extension/src/test/java/org/sentrysoftware/metricshub/extension/snmpv3/SnmpV3ConfigurationTest.java
  metricshub-windows/src/main/resources/jpackage/MetricsHub/config/metricshub-example.yaml
  pom.xml
Labels: enhancement

#611 Issue #608: Fix SNMP CLI retry-intervals option names and update SNMPv3 retry intervals example in documentation
  metricshub-agent/src/main/java/org/sentrysoftware/metricshub/cli/SnmpCli.java
  metricshub-agent/src/main/java/org/sentrysoftware/metricshub/cli/SnmpV3Cli.java
  metricshub-agent/src/main/java/org/sentrysoftware/metricshub/cli/service/protocol/SnmpConfigCli.java
  metricshub-agent/src/main/java/org/sentrysoftware/metricshub/cli/service/protocol/SnmpV3ConfigCli.java
  metricshub-doc/src/site/markdown/appendix/cli.md
Labels: developer_tested

#609 Issue #583: Add `awkcli` CLI for AWK processing
  metricshub-agent/src/main/java/org/sentrysoftware/metricshub/cli/JawkCli.java
  metricshub-agent/src/test/java/org/sentrysoftware/metricshub/cli/JawkCliTest.java
  metricshub-linux/pom.xml
  metricshub-linux/src/main/resources/jpackage/metricshub-jawk.properties
  metricshub-windows/pom.xml
  metricshub-windows/src/main/resources/jpackage/metricshub-jawk.properties
Labels: developer_tested

#616 Issue #614: metricshub.host.response_time is reported when metricshubhost.up is down
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/collect/ProtocolHealthCheckStrategy.java
Labels: developer_tested
