Repository MetricsHub/metricshub-community, pull requests merged in 2025-03, with the labels that each got.

#621 Issue #619: Incorrect text table display in SNMP logs when adding columns using computes
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/AbstractStrategy.java
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/source/SourceProcessor.java
Labels: developer_tested

#627 Issue #626: Remove mandatory attribute id requirement
  metricshub-agent/src/main/java/org/sentrysoftware/metricshub/cli/service/PrettyPrinterService.java
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/AbstractAllAtOnceStrategy.java
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/telemetry/Monitor.java
  metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/telemetry/MonitorFactory.java
  metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/discovery/DiscoveryStrategyTest.java
  metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/telemetry/MonitorTest.java
Labels: developer_tested

#625 Issue #623: JDBC URL is not generated when the database type is set to `mssql` in the resource protocol configuration
  metricshub-agent/src/main/java/org/sentrysoftware/metricshub/cli/service/MetricsHubCliService.java
  metricshub-agent/src/main/java/org/sentrysoftware/metricshub/cli/service/protocol/JdbcConfigCli.java
  metricshub-doc/src/site/markdown/appendix/cli.md
  metricshub-doc/src/site/markdown/configuration/configure-monitoring.md
  metricshub-jdbc-extension/src/main/java/org/sentrysoftware/metricshub/extension/jdbc/JdbcConfiguration.java
  metricshub-jdbc-extension/src/test/java/org/sentrysoftware/metricshub/extension/jdbc/JdbcConfigurationTest.java
Labels: bug, developer_tested

#630 Issue #620: Updated Health Check Query to Support Oracle and Cassandra Databases
  metricshub-jdbc-extension/src/main/java/org/sentrysoftware/metricshub/extension/jdbc/JdbcExtension.java
  metricshub-jdbc-extension/src/test/java/org/sentrysoftware/metricshub/extension/jdbc/JdbcConfigurationTest.java
  metricshub-jdbc-extension/src/test/java/org/sentrysoftware/metricshub/extension/jdbc/JdbcExtensionTest.java
Labels: developer_tested

#633 Issue #632: List the supported operating systems
  metricshub-doc/src/site/markdown/installation/debian-linux.md
  metricshub-doc/src/site/markdown/installation/docker.md
  metricshub-doc/src/site/markdown/installation/redhat-linux.md
  metricshub-doc/src/site/markdown/installation/windows.md
Labels: documentation

#637 Issue #631: Document MetricsHub Enterprise Docker
  metricshub-doc/src/site/markdown/installation/docker.md
Labels: documentation

#638 Issue #635: Updated release notes
  metricshub-doc/src/site/markdown/release-notes.md
Labels: developer_tested
