Repository MetricsHub/metricshub-community, pull requests merged in 2025-05, with the labels that each got.

#659 Issue #655: Document Self-Observability
  metricshub-doc/src/site/markdown/troubleshooting/self-observability.md
  metricshub-doc/src/site/site.xml
Labels: developer_tested

#660 Issue #651: Fix wrong monitors names
  metricshub-hardware/src/main/java/org/metricshub/hardware/HardwareEnergyPostExecutionService.java
  metricshub-hardware/src/main/java/org/metricshub/hardware/constants/BatteryConstants.java
  metricshub-hardware/src/main/java/org/metricshub/hardware/constants/BladeConstants.java
  metricshub-hardware/src/main/java/org/metricshub/hardware/constants/CommonConstants.java
  metricshub-hardware/src/main/java/org/metricshub/hardware/constants/CpuConstants.java
  metricshub-hardware/src/main/java/org/metricshub/hardware/constants/DiskControllerConstants.java
  metricshub-hardware/src/main/java/org/metricshub/hardware/constants/EnclosureConstants.java
  metricshub-hardware/src/main/java/org/metricshub/hardware/constants/FanConstants.java
  metricshub-hardware/src/main/java/org/metricshub/hardware/constants/GpuConstants.java
  metricshub-hardware/src/main/java/org/metricshub/hardware/constants/LedConstants.java
  metricshub-hardware/src/main/java/org/metricshub/hardware/constants/LogicalDiskConstants.java
  metricshub-hardware/src/main/java/org/metricshub/hardware/constants/LunConstants.java
  metricshub-hardware/src/main/java/org/metricshub/hardware/constants/MemoryConstants.java
  metricshub-hardware/src/main/java/org/metricshub/hardware/constants/NetworkConstants.java
  metricshub-hardware/src/main/java/org/metricshub/hardware/constants/OtherDeviceConstants.java
  metricshub-hardware/src/main/java/org/metricshub/hardware/constants/PhysicalDiskConstants.java
  metricshub-hardware/src/main/java/org/metricshub/hardware/constants/PowerSupplyConstants.java
  metricshub-hardware/src/main/java/org/metricshub/hardware/constants/RoboticsConstants.java
  metricshub-hardware/src/main/java/org/metricshub/hardware/constants/TapeDriveConstants.java
  metricshub-hardware/src/main/java/org/metricshub/hardware/constants/TemperatureConstants.java
  metricshub-hardware/src/main/java/org/metricshub/hardware/constants/VmConstants.java
  metricshub-hardware/src/main/java/org/metricshub/hardware/constants/VoltageConstants.java
  metricshub-hardware/src/main/java/org/metricshub/hardware/strategy/HardwarePostCollectStrategy.java
  metricshub-hardware/src/main/java/org/metricshub/hardware/strategy/HardwarePostDiscoveryStrategy.java
  metricshub-hardware/src/main/java/org/metricshub/hardware/sustainability/CpuPowerEstimator.java
  metricshub-hardware/src/main/java/org/metricshub/hardware/sustainability/DiskControllerPowerAndEnergyEstimator.java
  metricshub-hardware/src/main/java/org/metricshub/hardware/sustainability/FanPowerAndEnergyEstimator.java
  metricshub-hardware/src/main/java/org/metricshub/hardware/sustainability/HostMonitorPowerAndEnergyEstimator.java
  metricshub-hardware/src/main/java/org/metricshub/hardware/sustainability/HostMonitorThermalCalculator.java
  metricshub-hardware/src/main/java/org/metricshub/hardware/sustainability/MemoryPowerAndEnergyEstimator.java
  metricshub-hardware/src/main/java/org/metricshub/hardware/sustainability/NetworkPowerAndEnergyEstimator.java
  metricshub-hardware/src/main/java/org/metricshub/hardware/sustainability/PhysicalDiskPowerAndEnergyEstimator.java
  metricshub-hardware/src/main/java/org/metricshub/hardware/sustainability/RoboticsPowerAndEnergyEstimator.java
  metricshub-hardware/src/main/java/org/metricshub/hardware/sustainability/TapeDrivePowerAndEnergyEstimator.java
  metricshub-hardware/src/main/java/org/metricshub/hardware/sustainability/VmPowerAndEnergyEstimator.java
  metricshub-hardware/src/main/java/org/metricshub/hardware/threshold/AbstractMetricNormalizer.java
  metricshub-hardware/src/main/java/org/metricshub/hardware/threshold/FanMetricNormalizer.java
  metricshub-hardware/src/main/java/org/metricshub/hardware/threshold/GpuMetricNormalizer.java
  metricshub-hardware/src/main/java/org/metricshub/hardware/threshold/LunMetricNormalizer.java
  metricshub-hardware/src/main/java/org/metricshub/hardware/threshold/NetworkMetricNormalizer.java
  metricshub-hardware/src/main/java/org/metricshub/hardware/threshold/OtherDeviceMetricNormalizer.java
  metricshub-hardware/src/main/java/org/metricshub/hardware/threshold/TemperatureMetricNormalizer.java
  metricshub-hardware/src/main/java/org/metricshub/hardware/threshold/VoltageMetricNormalizer.java
  metricshub-hardware/src/main/java/org/metricshub/hardware/util/HwCollectHelper.java
  metricshub-hardware/src/main/java/org/metricshub/hardware/util/HwConstants.java
  metricshub-hardware/src/main/java/org/metricshub/hardware/util/MonitorNameBuilder.java
  metricshub-hardware/src/main/java/org/metricshub/hardware/util/PowerAndEnergyCollectHelper.java
  metricshub-hardware/src/test/java/org/metricshub/hardware/HardwareEnergyPostExecutionServiceTest.java
  metricshub-hardware/src/test/java/org/metricshub/hardware/strategy/HardwarePostCollectStrategyTest.java
  metricshub-hardware/src/test/java/org/metricshub/hardware/strategy/HardwarePostDiscoveryStrategyTest.java
  metricshub-hardware/src/test/java/org/metricshub/hardware/sustainability/CpuPowerEstimatorTest.java
  metricshub-hardware/src/test/java/org/metricshub/hardware/sustainability/HostMonitorEnergyAndPowerEstimatorTest.java
  metricshub-hardware/src/test/java/org/metricshub/hardware/sustainability/VmPowerAndEnergyEstimatorTest.java
  metricshub-hardware/src/test/java/org/metricshub/hardware/threshold/AbstractMetricNormalizerTest.java
  metricshub-hardware/src/test/java/org/metricshub/hardware/util/MonitorNameBuilderTest.java
Labels: bug, developer_tested

#670 Issue #650: Added support for configuration providers
  README.md
  metricshub-agent/pom.xml
  metricshub-agent/src/main/java/org/metricshub/agent/MetricsHubAgentApplication.java
  metricshub-agent/src/main/java/org/metricshub/agent/config/otel/OtelCollectorConfig.java
  metricshub-agent/src/main/java/org/metricshub/agent/context/AgentContext.java
  metricshub-agent/src/main/java/org/metricshub/agent/deserialization/PostConfigDeserializer.java
  metricshub-agent/src/main/java/org/metricshub/agent/helper/ConfigHelper.java
  metricshub-agent/src/main/java/org/metricshub/agent/helper/OtelConfigHelper.java
  metricshub-agent/src/main/java/org/metricshub/agent/service/ConfigurationService.java
  metricshub-agent/src/main/java/org/metricshub/agent/service/TaskSchedulingService.java
  metricshub-agent/src/main/java/org/metricshub/agent/service/task/DirectoryWatcherTask.java
  metricshub-agent/src/main/java/org/metricshub/agent/service/task/FileWatcherTask.java
  metricshub-agent/src/test/java/org/metricshub/agent/context/AgentContextTest.java
  metricshub-agent/src/test/java/org/metricshub/agent/deserialization/PostConfigDeserializerTest.java
  metricshub-agent/src/test/java/org/metricshub/agent/helper/ConfigHelperTest.java
  metricshub-agent/src/test/java/org/metricshub/agent/helper/TestConstants.java
  metricshub-agent/src/test/java/org/metricshub/agent/service/task/DirectoryWatcherTaskTest.java
  metricshub-agent/src/test/java/org/metricshub/agent/service/task/FileWatcherTaskTest.java
  metricshub-agent/src/test/resources/config/metricshub-connectorVariables/metricshub.yaml
  metricshub-agent/src/test/resources/config/metricshub-enable-self-monitoring-no-config/metricshub.yaml
  metricshub-agent/src/test/resources/config/metricshub-enable-self-monitoring-override/metricshub.yaml
  metricshub-agent/src/test/resources/config/metricshub-environmentVariables/metricshub.yaml
  metricshub-agent/src/test/resources/config/metricshub-multi-hosts/metricshub.yaml
  metricshub-agent/src/test/resources/config/metricshub-server1/metricshub.yaml
  metricshub-agent/src/test/resources/config/metricshub/metricshub.yaml
  metricshub-agent/src/test/resources/config/top-level-resource-agent-context-test/metricshub.yaml
  metricshub-agent/src/test/resources/config/top-level-resource-test/metricshub.yaml
  metricshub-community-linux/pom.xml
  metricshub-community-windows/pom.xml
  metricshub-doc/src/site/markdown/configuration/configure-monitoring.md
  metricshub-engine/src/main/java/org/metricshub/engine/extension/ExtensionLoader.java
  metricshub-engine/src/main/java/org/metricshub/engine/extension/ExtensionManager.java
  metricshub-engine/src/main/java/org/metricshub/engine/extension/IConfigurationProvider.java
  metricshub-hardware/src/main/java/org/metricshub/hardware/sustainability/HostMonitorThermalCalculator.java
  metricshub-hardware/src/main/java/org/metricshub/hardware/util/MonitorNameBuilder.java
  metricshub-hardware/src/test/java/org/metricshub/hardware/util/MonitorNameBuilderTest.java
  metricshub-yaml-configuration-extension/pom.xml
  metricshub-yaml-configuration-extension/src/main/java/org/metricshub/configuration/YamlConfigurationProvider.java
  metricshub-yaml-configuration-extension/src/main/resources/META-INF/services/org.metricshub.engine.extension.IConfigurationProvider
  metricshub-yaml-configuration-extension/src/test/java/org/metricshub/configuration/YamlConfigurationProviderTest.java
  pom.xml
Labels: developer_tested

#675 Issue #674: Multi-threaded NullPointerException in MetricsHub JAWK Extension due to Non-thread-safe Globals
  metricshub-jawk-extension/src/main/java/org/metricshub/extension/jawk/JawkSourceExtension.java
Labels: developer_tested

#679 Issue #678: Update project dependencies for QA phase
  metricshub-doc/pom.xml
  metricshub-doc/src/site/resources/images/platforms/nvidia-dgx.png
  metricshub-doc/src/site/resources/images/platforms/postgre-sql.png
  pom.xml
Labels: developer_tested

#676 Issue #672: Document support for multiple configuration files
  metricshub-doc/src/site/markdown/configuration/configure-monitoring.md
  metricshub-doc/src/site/markdown/guides/configure-sustainability-metrics.md
  metricshub-doc/src/site/markdown/guides/quick-start-community-prometheus.md
  metricshub-doc/src/site/markdown/installation/debian-linux.md
  metricshub-doc/src/site/markdown/installation/docker.md
  metricshub-doc/src/site/markdown/installation/redhat-linux.md
  metricshub-doc/src/site/markdown/installation/windows.md
  metricshub-doc/src/site/markdown/security/passwords.md
  metricshub-doc/src/site/markdown/security/security.md
  metricshub-doc/src/site/markdown/troubleshooting/metricshub-logs.md
  metricshub-doc/src/site/markdown/troubleshooting/no-data-resources.md
  metricshub-doc/src/site/markdown/upgrade.md
  metricshub-doc/src/site/site.xml
Labels: documentation

#677 Issue #486 Document the Datadog integration
  metricshub-doc/src/site/markdown/integrations/datadog.md
  metricshub-doc/src/site/resources/images/metricshub-datadog-diagram.png
  metricshub-doc/src/site/site.xml
Labels: documentation

#681 Issue #680: Fix NPE in MonitorNameBuilder when metric is null
  metricshub-hardware/src/main/java/org/metricshub/hardware/util/MonitorNameBuilder.java
  metricshub-hardware/src/test/java/org/metricshub/hardware/util/MonitorNameBuilderTest.java
Labels: developer-tested

#685 Issue #503: Corrected estimated and measured `hw.host.power` metrics reported for the same host simultaneously
  metricshub-engine/src/main/java/org/metricshub/engine/common/helpers/MetricsHubConstants.java
  metricshub-engine/src/main/java/org/metricshub/engine/connector/model/Connector.java
  metricshub-engine/src/main/java/org/metricshub/engine/connector/model/PowerMeasurement.java
  metricshub-engine/src/main/java/org/metricshub/engine/connector/parser/ConnectorParser.java
  metricshub-engine/src/main/java/org/metricshub/engine/connector/update/CompiledFilenameUpdater.java
  metricshub-engine/src/main/java/org/metricshub/engine/connector/update/PowerMeasurementStatusUpdate.java
  metricshub-engine/src/main/java/org/metricshub/engine/strategy/AbstractAllAtOnceStrategy.java
  metricshub-engine/src/main/java/org/metricshub/engine/strategy/collect/CollectStrategy.java
  metricshub-engine/src/main/java/org/metricshub/engine/strategy/utils/StrategyHelper.java
  metricshub-engine/src/test/java/org/metricshub/engine/connector/update/PowerMeasurementStatusUpdateTest.java
  metricshub-hardware/src/main/java/org/metricshub/hardware/util/HwCollectHelper.java
  metricshub-hardware/src/main/java/org/metricshub/hardware/util/PowerAndEnergyCollectHelper.java
  metricshub-hardware/src/test/java/org/metricshub/hardware/util/PowerAndEnergyCollectHelperTest.java
Labels: developer-tested
